version: '3.8'

volumes:
  pg_data:


services:
  db:
    image: postgres:16.2
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: .
    env_file: .env
    depends_on:
      - db
