"""alter fields on tables

Revision ID: 0ff602dc7222
Revises: be6202b1a491
Create Date: 2024-03-07 23:21:08.107319

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0ff602dc7222"
down_revision: Union[str, None] = "be6202b1a491"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("commits", sa.Column("sha", sa.String(), nullable=False))
    op.drop_constraint("date_author_repo_uc", "commits", type_="unique")
    op.create_unique_constraint(None, "commits", ["sha"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "commits", type_="unique")
    op.create_unique_constraint(
        "date_author_repo_uc", "commits", ["date", "author", "repo"]
    )
    op.drop_column("commits", "sha")
    # ### end Alembic commands ###
