"""alter fields on tables

Revision ID: 9e55742b99bd
Revises: 4ec8b69ebd82
Create Date: 2024-03-07 22:16:23.157521

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9e55742b99bd"
down_revision: Union[str, None] = "4ec8b69ebd82"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "repos", ["repo"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "repos", type_="unique")
    # ### end Alembic commands ###
