"""Database update

Revision ID: bdd7bfd60a43
Revises: ef6d9f99f3fa
Create Date: 2024-03-06 13:30:16.275520

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bdd7bfd60a43"
down_revision: Union[str, None] = "ef6d9f99f3fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "commits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("author", sa.String(), nullable=False),
        sa.Column("repo", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["repo"],
            ["repos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "repos", "position_cur", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "repos", "position_prev", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "repos", "position_prev", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "repos", "position_cur", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_table("commits")
    # ### end Alembic commands ###
