"""alter fields on tables

Revision ID: be6202b1a491
Revises: 24f1a05b9f02
Create Date: 2024-03-07 22:36:02.171004

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "be6202b1a491"
down_revision: Union[str, None] = "24f1a05b9f02"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "date_author_repo_uc", "commits", ["date", "author", "repo"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("date_author_repo_uc", "commits", type_="unique")
    # ### end Alembic commands ###
